import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import CookieConsent from './components/CookieConsent';
import CookieConsent from './components/CookieConsent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden max-w-full`}>
        {children}
        <CookieConsent />
        <CookieConsent />
      </body>
    </html>
  );
}